# Generated by Django 5.1.1 on 2024-09-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousemodel',
            old_name='material',
            new_name='material_id',
        ),
    ]
