# Generated by Django 5.1.1 on 2024-09-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_rename_material_warehousemodel_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterialmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='warehousemodel',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
