# Generated by Django 5.1.1 on 2024-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_productmaterialmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialmodel',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterModelOptions(
            name='productmaterialmodel',
            options={'verbose_name': 'Product Material', 'verbose_name_plural': 'Product Materials'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='warehousemodel',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterField(
            model_name='warehousemodel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
